version: "3"

networks:
  backend:

services:
  database:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_DB=Base
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    working_dir: /code/
    tty: true
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - database
  celery:
    build: .
    command: celery -A Base worker -l INFO
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - SECRET_KEY=*r!m+%$k*3yvla0jdl6sm$j1hi$rnbsc0x3)7u(vv_zj_bnowf
    depends_on:
      - django
      - redis
  redis:
    image: "redis:alpine"
  celery-beat:
    build: .
    command: celery -A Base beat -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=*r!m+%$k*3yvla0jdl6sm$j1hi$rnbsc0x3)7u(vv_zj_bnowf
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - django
      - redis