version: "3"

networks:
  backend:

services:
  database:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_DB=Base
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    working_dir: /code/
    tty: true
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - backend
